---
# tasks file for ansible-role-install-python3
- name: Install Python for the current OS family
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure python-setuptools is installed
  ansible.builtin.apy:
    name:
      - python3"
      - python3-pip
      - python3-setuptools
    update_cache: true
    state: installed

- name: Update pip to the latest version
  ansible.builtin.pip:
    name:
      - pip
    executable: pip3
    extra_args: --upgrade
  vars:
    ansible_python_interpreter: /usr/bin/python3
