---
- name: Converge
  hosts: all
  gather_facts: true
  gather_subset:
    - "os_family"
    - "distribution_major_version"
    - "!min"
    - "!all"
  pre_tasks:
    - name: Set Python install version to 2 for older OSes
      ansible.builtin.set_fact:
        install_python: "{{ install_python2 }}"
      when: >
        (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int < 8) or
        (ansible_distribution == 'Debian') and (ansible_distribution_major_version | int < 10) or
        (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version | int < 18)
  tasks:
    - name: Install Python, pip, and setuptools
      ansible.builtin.include_role:
        name: "mirsg.install_python"
