---
- name: Converge
  hosts: all
  gather_facts: true
  gather_subset:
    - "os_family"
    - "!min"
    - "!all"
  tasks:
    - name: Install Python 3, pip, and setuptools
      ansible.builtin.include_role:
        name: "mirsg.install_python3"
