---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-centos7-ansible:latest}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
  inventory:
    group_vars:
      all:
        additional_networks: []
        default_networks:
          - "0.0.0.0/0"
  env:
    ANSIBLE_VERBOSITY: "1"

verifier:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: "1"

lint: |
  set -e
  yamllint .
  ansible-lint .
