---
name: Molecule Test
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "mirsg.install_python"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: "mirsg.install_python"
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install lint dependencies
        run: pip3 install yamllint
      - name: Lint code
        run: |
          yamllint .

  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        molecule_docker_image:
          - rockylinux:8
          - centos:7
          - geerlingguy/docker-centos7-ansible:latest
          - geerlingguy/docker-ubuntu2204-ansible:latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: "mirsg.install_python"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install test dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install rsync
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Test with molecule
        run: |
          molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.molecule_docker_image }}
